// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    short_code,
    long_url
)
VALUES (
           $1,
           $2
       )
    RETURNING
    id,
    short_code,
    long_url,
    clicks,
    created_at
`

type CreateLinkParams struct {
	ShortCode string `json:"short_code"`
	LongUrl   string `json:"long_url"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.ShortCode, arg.LongUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.Clicks,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByCode = `-- name: GetLinkByCode :one
SELECT
    id,
    short_code,
    long_url,
    clicks,
    created_at
FROM links
WHERE short_code = $1
`

func (q *Queries) GetLinkByCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByCode, shortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.LongUrl,
		&i.Clicks,
		&i.CreatedAt,
	)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :execrows
UPDATE links
SET clicks = clicks + 1
WHERE short_code = $1
`

func (q *Queries) IncrementClicks(ctx context.Context, shortCode string) (int64, error) {
	result, err := q.db.Exec(ctx, incrementClicks, shortCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
