// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID        int32              `json:"id"`
	ShortCode string             `json:"short_code"`
	LongUrl   string             `json:"long_url"`
	Clicks    int32              `json:"clicks"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
