// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Link struct {
	ID        int32     `json:"id"`
	ShortCode string    `json:"short_code"`
	LongUrl   string    `json:"long_url"`
	Clicks    int32     `json:"clicks"`
	CreatedAt time.Time `json:"created_at"`
}
