// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	GetLinkByCode(ctx context.Context, shortCode string) (Link, error)
	IncrementClicks(ctx context.Context, shortCode string) (int64, error)
}

var _ Querier = (*Queries)(nil)
